### ISSUE TITLE
Continue onwards!

### ISSUE THREAD

**Issue by HalosGhost** [kikito/love-tile-tutorial#5]
I must say that I quite enjoyed this tutorial and would love to see its completion. Do you have any plans to continue its development?

**Comment by kikito** [comment]
Hi,

Thanks for your encouraging words.

When I stopped writing this tutorial I did so because the things I wanted to cover required some libraries which did not exist yet.

I have been slowly writing them. I have a pretty decent camera lib, gamera.lua, and a collision library which works well with tile-based projects and it's simple to use, bump.lua. So while I have not been able to work on this tutorial directly, the pieces needed to keep working on it are there.

I don't know when I will be able to keep writing it, but that's my plan. I'm sorry that the update speed is ... geological. I've got a lot of stuff on my plate.

**Comment by HalosGhost** [comment]
Not a problem! I'm glad to hear you're still in-process. I look forward to seeing what the future holds!

**Comment by jinpark** [comment]
Just want to say :+1: on the tutorial and I'm looking forward to seeing more!

**Comment by domino14** [comment]
plz continue
